//! Column registry for entity tables, loaded from `schema.json` (generated by
//! `shared/drizzle/entity-schema-meta.mjs` via `pnpm export-schema` / `just drizzle-gen`; see
//! .kilo/plans/1782949593655-relational-cdc-migration.md, Fase 1 tarea 7 y Fase 2).
//!
//! This lets `SqlEngine` (client) and the admin CDC-projection code build typed
//! INSERT/SELECT statements generically, without hardcoding column lists per entity in Rust.
//! It also centralizes entity name aliasing (`"invoice"` vs `"invoices"`, etc.) that used to
//! be duplicated across `events.rs`, `indexes.rs`, and `cdc.rs`.

use std::collections::HashMap;
use std::sync::OnceLock;

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ColumnType {
    Text,
    Integer,
    Real,
}

#[derive(Debug, Clone, serde::Deserialize)]
pub struct ColumnMeta {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: ColumnType,
    #[serde(default)]
    pub nullable: bool,
    #[serde(default)]
    pub searchable: bool,
}

#[derive(Debug, Clone, serde::Deserialize)]
pub struct ChildTableMeta {
    pub table: String,
    #[serde(rename = "parentKey")]
    pub parent_key: String,
    pub columns: Vec<ColumnMeta>,
}

#[derive(Debug, Clone, serde::Deserialize)]
pub struct EntityMeta {
    pub table: String,
    pub columns: Vec<ColumnMeta>,
    #[serde(default)]
    pub children: Vec<ChildTableMeta>,
}

/// Sync/system columns present on every entity/child table; excluded from the
/// business-field JSON projection (`query_entity` reconstructs these separately).
pub const ENTITY_SYNC_COLUMNS: &[&str] = &["org_id", "doc_id", "change_time", "node_id"];

fn schema_map() -> &'static HashMap<String, EntityMeta> {
    static SCHEMA: OnceLock<HashMap<String, EntityMeta>> = OnceLock::new();
    SCHEMA.get_or_init(|| {
        let raw = include_str!("../schema.json");
        serde_json::from_str(raw).expect("crates/syntrix-core/schema.json must be valid JSON matching EntityMeta")
    })
}

/// Canonicalizes an entity name/alias (e.g. "invoice" or "invoices") to its table name.
pub fn entity_table_name(entity: &str) -> anyhow::Result<&'static str> {
    let normalized = normalize_entity(entity).ok_or_else(|| anyhow::anyhow!("unknown entity: {}", entity))?;
    Ok(normalized)
}

fn normalize_entity(entity: &str) -> Option<&'static str> {
    match entity {
        "customers" | "customer" => Some("customers"),
        "suppliers" | "supplier" => Some("suppliers"),
        "products" | "product" => Some("products"),
        "invoices" | "invoice" => Some("invoices"),
        "orders" | "order" => Some("orders"),
        "payroll" => Some("payroll"),
        _ => None,
    }
}

pub fn entity_meta(entity: &str) -> anyhow::Result<&'static EntityMeta> {
    let table = entity_table_name(entity)?;
    schema_map()
        .get(table)
        .ok_or_else(|| anyhow::anyhow!("no schema.json metadata for entity: {}", table))
}

pub fn all_entity_tables() -> Vec<&'static str> {
    ["customers", "suppliers", "products", "invoices", "orders", "payroll"].to_vec()
}

/// Business (non-sync) columns for the parent entity table, in schema order.
pub fn business_columns(meta: &EntityMeta) -> Vec<&ColumnMeta> {
    meta.columns
        .iter()
        .filter(|c| !ENTITY_SYNC_COLUMNS.contains(&c.name.as_str()))
        .collect()
}

/// Business (non-sync) columns for a child table, in schema order. Excludes `org_id`,
/// the FK to the parent (`parent_key`), `change_time`, and `node_id`.
pub fn child_business_columns<'a>(child: &'a ChildTableMeta) -> Vec<&'a ColumnMeta> {
    child
        .columns
        .iter()
        .filter(|c| c.name != "org_id" && c.name != child.parent_key && c.name != "change_time" && c.name != "node_id")
        .collect()
}

/// Searchable columns (for FTS5) across the parent table only (children are not
/// independently searchable today).
pub fn searchable_columns(meta: &EntityMeta) -> Vec<&str> {
    meta.columns
        .iter()
        .filter(|c| c.searchable)
        .map(|c| c.name.as_str())
        .collect()
}

/// Resolution of a physical SQL table name (as it appears in `turso_cdc.table_name`) to its
/// schema metadata: either a top-level entity table, or a child table with its owning entity
/// (Fase 3, tarea 13). `columns` on both variants are in the exact physical column order used
/// by the CREATE TABLE statement, which is what `read_cdc_events` needs to decode `turso_cdc`
/// row-image blobs positionally.
#[derive(Debug, Clone, Copy)]
pub enum TableRef {
    Entity(&'static EntityMeta),
    Child { parent_entity: &'static str, parent: &'static EntityMeta, child: &'static ChildTableMeta },
}

impl TableRef {
    /// The entity name used for permission checks (`can_write`), even for child rows.
    pub fn entity_name(&self) -> &'static str {
        match self {
            TableRef::Entity(meta) => meta.table.as_str(),
            TableRef::Child { parent_entity, .. } => parent_entity,
        }
    }

    /// Physical columns in CREATE TABLE order.
    pub fn columns(&self) -> &'static [ColumnMeta] {
        match self {
            TableRef::Entity(meta) => &meta.columns,
            TableRef::Child { child, .. } => &child.columns,
        }
    }

    pub fn table_name(&self) -> &'static str {
        match self {
            TableRef::Entity(meta) => meta.table.as_str(),
            TableRef::Child { child, .. } => child.table.as_str(),
        }
    }
}

/// All physical SQL tables that carry CDC (top-level entities + their child tables).
pub fn all_physical_tables() -> Vec<&'static str> {
    let mut out = Vec::new();
    for entity in all_entity_tables() {
        if let Ok(meta) = entity_meta(entity) {
            out.push(meta.table.as_str());
            for child in &meta.children {
                out.push(child.table.as_str());
            }
        }
    }
    out
}

/// Resolves a physical table name to its owning entity metadata (Fase 3, tarea 13).
pub fn resolve_table(table_name: &str) -> Option<TableRef> {
    for entity in all_entity_tables() {
        let meta = entity_meta(entity).ok()?;
        if meta.table == table_name {
            return Some(TableRef::Entity(meta));
        }
        for child in &meta.children {
            if child.table == table_name {
                return Some(TableRef::Child { parent_entity: entity, parent: meta, child });
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_schema_json_for_all_entities() {
        for table in all_entity_tables() {
            let meta = entity_meta(table).unwrap_or_else(|e| panic!("missing schema for {table}: {e}"));
            assert_eq!(meta.table, table);
            assert!(!meta.columns.is_empty());
        }
    }

    #[test]
    fn normalizes_singular_aliases() {
        assert_eq!(entity_table_name("invoice").unwrap(), "invoices");
        assert_eq!(entity_table_name("order").unwrap(), "orders");
        assert_eq!(entity_table_name("customer").unwrap(), "customers");
        assert!(entity_table_name("bogus").is_err());
    }

    #[test]
    fn invoices_has_invoice_items_child_with_correct_parent_key() {
        let meta = entity_meta("invoices").unwrap();
        assert_eq!(meta.children.len(), 1);
        let child = &meta.children[0];
        assert_eq!(child.table, "invoice_items");
        assert_eq!(child.parent_key, "invoice_id");
        let biz_cols: Vec<&str> = child_business_columns(child).iter().map(|c| c.name.as_str()).collect();
        assert_eq!(biz_cols, vec!["line_id", "product_id", "qty", "price"]);
    }

    #[test]
    fn business_columns_excludes_sync_columns() {
        let meta = entity_meta("customers").unwrap();
        let cols: Vec<&str> = business_columns(&meta).iter().map(|c| c.name.as_str()).collect();
        assert_eq!(cols, vec!["name", "tax_id", "address", "phone", "email"]);
    }

    #[test]
    fn searchable_columns_for_customers() {
        let meta = entity_meta("customers").unwrap();
        let cols = searchable_columns(&meta);
        assert!(cols.contains(&"name"));
        assert!(cols.contains(&"email"));
        assert!(cols.contains(&"tax_id"));
        assert!(!cols.contains(&"address"));
    }

    #[test]
    fn resolve_table_finds_entity_and_child_tables() {
        match resolve_table("customers") {
            Some(TableRef::Entity(meta)) => assert_eq!(meta.table, "customers"),
            other => panic!("expected Entity(customers), got {other:?}"),
        }
        match resolve_table("invoice_items") {
            Some(TableRef::Child { parent_entity, child, .. }) => {
                assert_eq!(parent_entity, "invoices");
                assert_eq!(child.table, "invoice_items");
            }
            other => panic!("expected Child(invoice_items), got {other:?}"),
        }
        assert!(resolve_table("no_such_table").is_none());
    }

    #[test]
    fn all_physical_tables_includes_children() {
        let tables = all_physical_tables();
        assert!(tables.contains(&"customers"));
        assert!(tables.contains(&"invoice_items"));
        assert!(tables.contains(&"order_items"));
    }
}
