[workspace]
resolver = "2"
members = [
    "apps/admin/src-tauri",
    "apps/client/src-tauri",
    "crates/syntrix-core",
    "crates/syntrix-schema",
    "crates/syntrix-testkit",
    "crates/syntrix-logging",
]

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
opt-level = 2
debug = false
