[workspace]
resolver = "2"
members = [
    "apps/admin/src-tauri",
    "apps/client/src-tauri",
    "crates/syntrix-core",
    "crates/syntrix-network",
    "crates/syntrix-testkit",
    "crates/syntrix-logging",
    "crates/syntrix-ai",
]

[workspace.dependencies]
turso_core = { git = "https://github.com/tursodatabase/turso.git", default-features = false, features = ["fs", "uuid", "time", "json"] }

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
opt-level = 2
debug = false
