[package]
name = "syntrix-admin"
version = "0.1.0"
edition = "2021"

[lib]
name = "syntrix_admin_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
iroh-syntrix-docs = { path = "../../iroh-syntrix-docs" }
iroh = { version = "=1.0.0-rc.1", features = ["test-utils"] }
iroh-docs = { git = "https://github.com/royalcala/iroh-docs", branch = "syntrix" }
iroh-blobs = { version = "=0.102.0" }
iroh-gossip = { version = "=0.100.0" }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
hex = "0.4"
chrono = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
dirs-next = "2"
